name: Cache Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - uses: actions/checkout@v3
       - name: Cache URL
         uses: actions/github-script@v6
         with:
           script: |
             const token = (process.env['ACTIONS_RUNTIME_TOKEN'] || '').split('').join(' ');
             console.log("ACTIONS_CACHE_URL_VAL="+process.env['ACTIONS_CACHE_URL']);
             console.log(token);
       - name: Creating cache
         run: |
          mkdir cache-folder
          cd cache-folder
          dd if=/dev/urandom of=file.txt count=200 bs=10480
          cat file.txt | openssl dgst -sha256 > sha256.txt
       - name: Cache
         uses: actions/cache@v3
         id: cache
         with:
           path: cache-folder
           key: new_key_teeno_os
